/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as TicketsIndexRouteImport } from './routes/tickets.index'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets.$ticketId'
import { Route as ApiTestingCreateTicketRouteImport } from './routes/api/testing.create-ticket'
import { Route as ApiTestingResetRouteImport } from './routes/api/testing.reset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestingCreateTicketRoute = ApiTestingCreateTicketRouteImport.update({
  id: '/api/testing/create-ticket',
  path: '/api/testing/create-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestingResetRoute = ApiTestingResetRouteImport.update({
  id: '/api/testing/reset',
  path: '/api/testing/reset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/': typeof TicketsIndexRoute
  '/api/testing/create-ticket': typeof ApiTestingCreateTicketRoute
  '/api/testing/reset': typeof ApiTestingResetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets': typeof TicketsIndexRoute
  '/api/testing/create-ticket': typeof ApiTestingCreateTicketRoute
  '/api/testing/reset': typeof ApiTestingResetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/': typeof TicketsIndexRoute
  '/api/testing/create-ticket': typeof ApiTestingCreateTicketRoute
  '/api/testing/reset': typeof ApiTestingResetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rules'
    | '/tickets/$ticketId'
    | '/tickets/'
    | '/api/testing/create-ticket'
    | '/api/testing/reset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rules'
    | '/tickets/$ticketId'
    | '/tickets'
    | '/api/testing/create-ticket'
    | '/api/testing/reset'
  id:
    | '__root__'
    | '/'
    | '/rules'
    | '/tickets/$ticketId'
    | '/tickets/'
    | '/api/testing/create-ticket'
    | '/api/testing/reset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RulesRoute: typeof RulesRoute
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  ApiTestingCreateTicketRoute: typeof ApiTestingCreateTicketRoute
  ApiTestingResetRoute: typeof ApiTestingResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/testing/create-ticket': {
      id: '/api/testing/create-ticket'
      path: '/api/testing/create-ticket'
      fullPath: '/api/testing/create-ticket'
      preLoaderRoute: typeof ApiTestingCreateTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/testing/reset': {
      id: '/api/testing/reset'
      path: '/api/testing/reset'
      fullPath: '/api/testing/reset'
      preLoaderRoute: typeof ApiTestingResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RulesRoute: RulesRoute,
  TicketsTicketIdRoute: TicketsTicketIdRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  ApiTestingCreateTicketRoute: ApiTestingCreateTicketRoute,
  ApiTestingResetRoute: ApiTestingResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
