/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts.$accountId'
import { Route as AccountsNewRouteImport } from './routes/accounts.new'
import { Route as AccountsAccountIdIndexRouteImport } from './routes/accounts.$accountId.index'
import { Route as AccountsAccountIdEditRouteImport } from './routes/accounts.$accountId.edit'
import { Route as ApiTestingResetRouteImport } from './routes/api/testing.reset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/accounts/new',
  path: '/accounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdIndexRoute = AccountsAccountIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsAccountIdRoute,
} as any)
const AccountsAccountIdEditRoute = AccountsAccountIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AccountsAccountIdRoute,
} as any)
const ApiTestingResetRoute = ApiTestingResetRouteImport.update({
  id: '/api/testing/reset',
  path: '/api/testing/reset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts/$accountId': typeof AccountsAccountIdRouteWithChildren
  '/accounts/new': typeof AccountsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/accounts/$accountId/edit': typeof AccountsAccountIdEditRoute
  '/api/testing/reset': typeof ApiTestingResetRoute
  '/accounts/$accountId/': typeof AccountsAccountIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts/new': typeof AccountsNewRoute
  '/accounts': typeof AccountsIndexRoute
  '/accounts/$accountId/edit': typeof AccountsAccountIdEditRoute
  '/api/testing/reset': typeof ApiTestingResetRoute
  '/accounts/$accountId': typeof AccountsAccountIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts/$accountId': typeof AccountsAccountIdRouteWithChildren
  '/accounts/new': typeof AccountsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/accounts/$accountId/edit': typeof AccountsAccountIdEditRoute
  '/api/testing/reset': typeof ApiTestingResetRoute
  '/accounts/$accountId/': typeof AccountsAccountIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/accounts/'
    | '/accounts/$accountId/edit'
    | '/api/testing/reset'
    | '/accounts/$accountId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts/new'
    | '/accounts'
    | '/accounts/$accountId/edit'
    | '/api/testing/reset'
    | '/accounts/$accountId'
  id:
    | '__root__'
    | '/'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/accounts/'
    | '/accounts/$accountId/edit'
    | '/api/testing/reset'
    | '/accounts/$accountId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRouteWithChildren
  AccountsNewRoute: typeof AccountsNewRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  ApiTestingResetRoute: typeof ApiTestingResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/new': {
      id: '/accounts/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId/': {
      id: '/accounts/$accountId/'
      path: '/'
      fullPath: '/accounts/$accountId/'
      preLoaderRoute: typeof AccountsAccountIdIndexRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
    '/accounts/$accountId/edit': {
      id: '/accounts/$accountId/edit'
      path: '/edit'
      fullPath: '/accounts/$accountId/edit'
      preLoaderRoute: typeof AccountsAccountIdEditRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
    '/api/testing/reset': {
      id: '/api/testing/reset'
      path: '/api/testing/reset'
      fullPath: '/api/testing/reset'
      preLoaderRoute: typeof ApiTestingResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountsAccountIdRouteChildren {
  AccountsAccountIdEditRoute: typeof AccountsAccountIdEditRoute
  AccountsAccountIdIndexRoute: typeof AccountsAccountIdIndexRoute
}

const AccountsAccountIdRouteChildren: AccountsAccountIdRouteChildren = {
  AccountsAccountIdEditRoute: AccountsAccountIdEditRoute,
  AccountsAccountIdIndexRoute: AccountsAccountIdIndexRoute,
}

const AccountsAccountIdRouteWithChildren =
  AccountsAccountIdRoute._addFileChildren(AccountsAccountIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsAccountIdRoute: AccountsAccountIdRouteWithChildren,
  AccountsNewRoute: AccountsNewRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  ApiTestingResetRoute: ApiTestingResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
